/// <reference lib="webworker" />
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { recordClickedNotification } from './lib/db';
import { app } from './lib/firebase';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Force the waiting service worker to become the active service worker.
self.skipWaiting();

// Ensure that any open clients are controlled by the new service worker immediately.
clientsClaim();

// Initialize Messaging synchronously at the top level
const messaging = getMessaging(app);

onBackgroundMessage(messaging, (payload) => {
  console.log('[sw.ts] Received background message ', payload);
  if (payload.notification) {
    const notificationTitle = payload.notification.title || 'New Notification';
    const notificationOptions = {
      body: payload.notification.body,
      icon: '/pwa-192x192.png',
      data: {
        notification_id: payload.data?.notification_id,
      },
    };

    self.registration.showNotification(notificationTitle, notificationOptions);
  }
});

self.addEventListener('notificationclick', (event) => {
  const notification = event.notification;
  const notificationId = notification.data?.notification_id;

  notification.close();

  if (notificationId) {
    // Save to IndexedDB for the app to pick up
    event.waitUntil(recordClickedNotification(notificationId));
  }

  // Focus or open the window
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      if (clientList.length > 0) {
        return clientList[0].focus();
      }
      return self.clients.openWindow('/');
    })
  );
});
