/// <reference lib="webworker" />
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { recordClickedNotification } from './lib/db';
import { app } from './lib/firebase';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Lifecycle events
self.addEventListener('install', () => {
  console.log('[sw.ts] Service Worker installing...');
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  console.log('[sw.ts] Service Worker activating...');
  event.waitUntil(
    self.registration.pushManager.getSubscription().then((sub) => {
      if (sub) {
        console.log('[sw.ts] Active push subscription found:', sub.endpoint);
      } else {
        console.log('[sw.ts] No active push subscription found on activation.');
      }
      return clientsClaim();
    })
  );
});

// Initialize Messaging synchronously at the top level
console.log('[sw.ts] Initializing messaging with app:', app.options.projectId);
const messaging = getMessaging(app);

onBackgroundMessage(messaging, (payload) => {
  console.log('[sw.ts] Received background message (onBackgroundMessage):', payload);
  if (payload.notification) {
    const notificationTitle = payload.notification.title || 'New Notification';
    const notificationOptions = {
      body: payload.notification.body,
      icon: '/pwa-192x192.png',
      data: {
        notification_id: payload.data?.notification_id,
      },
    };

    console.log('[sw.ts] Showing notification via onBackgroundMessage:', notificationTitle);
    self.registration.showNotification(notificationTitle, notificationOptions);
  }
});

// Fallback manual push event handler for debugging
self.addEventListener('push', (event) => {
  console.log('[sw.ts] Manual push event received:', event);

  if (event.data) {
    try {
      const payload = event.data.json();
      console.log('[sw.ts] Push event data (JSON):', payload);

      // If the SDK didn't handle it (or we want to be sure), we can show it here
      // But usually we just want to log that it arrived.
    } catch (e) {
      console.log('[sw.ts] Push event data (Text):', event.data.text());
    }
  } else {
    console.log('[sw.ts] Push event received but no data.');
  }
});

self.addEventListener('notificationclick', (event) => {
  const notification = event.notification;
  const notificationId = notification.data?.notification_id;

  notification.close();

  if (notificationId) {
    // Save to IndexedDB for the app to pick up
    event.waitUntil(recordClickedNotification(notificationId));
  }

  // Focus or open the window
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      if (clientList.length > 0) {
        return clientList[0].focus();
      }
      return self.clients.openWindow('/');
    })
  );
});
